Controllers/AppointmentController.cs
using Med_Center.Data;
using Med_Center.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;
using Med_Center.Models;
namespace Med_Center.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly MedCenterContext _context;
        public AppointmentController(MedCenterContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var appointments = await _context.Appointments.ToListAsync();
            return View(appointments);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var model = new AppointmentForCreation();
            model.Doctors = await _context.Doctors.ToListAsync();
            model.Patients = await _context.Patients.ToListAsync();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AppointmentForCreation model)
        {
            var dName = await _context.Doctors.Where(d => d.Id == model.DoctorId).FirstOrDefaultAsync();
            var pName = await _context.Patients.Where(d => d.Id == model.PatientId).FirstOrDefaultAsync();

            var appointment = new Appointment()
            {
                No = "",
                Date = DateTime.ParseExact(model.Date, "dd/MM/yyyy", CultureInfo.InvariantCulture),
                DoctorId = model.DoctorId,
                DoctorName = dName?.Name,
                PatientId = model.PatientId,
                PatientName = pName?.FirstName + " " + pName?.LastName,
            };
            
            await _context.Appointments.AddAsync(appointment);
            await _context.SaveChangesAsync();

            appointment.No = $"{appointment.Id}-appointment";

            _context.Appointments.Update(appointment);
            await _context.SaveChangesAsync();

            dName.AppointmentCount += 1;
            _context.Doctors.Update(dName);
            await _context.SaveChangesAsync();

            pName.AppointmentCount += 1;
            _context.Patients.Update(pName);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var appointment = await _context.Appointments.FindAsync(id);
            var model = new AppointmentForEdit()
            {
                Id = id,
                No = appointment.No,
                Date = appointment.Date.ToString("dd/MM/yyyy"),
                SelectedDoctorId = appointment.DoctorId,
                DoctorName = appointment.DoctorName,
                SelectedPatientId = appointment.PatientId,
                PatientName = appointment.PatientName,
                Doctors = await _context.Doctors.ToListAsync(),
                Patients = await _context.Patients.ToListAsync()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AppointmentForEdit model)
        {
            var dName = await _context.Doctors.Where(d => d.Id == model.DoctorId).Select(d => d.Name).FirstOrDefaultAsync();
            var pName = await _context.Patients.Where(d => d.Id == model.PatientId).Select(d => d.FirstName + " " + d.LastName).FirstOrDefaultAsync();

            var appointment = new Appointment()
            {
                Id = model.Id,
                No = model.No,
                Date = DateTime.ParseExact(model.Date, "dd/MM/yyyy", CultureInfo.InvariantCulture),
                DoctorId = model.DoctorId,
                DoctorName = dName!,
                PatientId = model.PatientId,
                PatientName = pName!,
            };
            _context.Appointments.Update(appointment);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var appointment = await _context.Appointments.FindAsync(id);

            _context.Appointments.Remove(appointment);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        }
    }

Controllers/DoctorController.cs
using Med_Center.Data;
using Med_Center.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Med_Center.Controllers;

namespace Med_Center.Controllers
{
    public class DoctorController : Controller
    {
        private readonly MedCenterContext _context;
        public DoctorController(MedCenterContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var doctors = await _context.Doctors.ToListAsync();
            return View(doctors);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var model = new DoctorForCreation();
            return View(model);
        }
        [HttpPost]
        
        public async Task<IActionResult> Create(DoctorForCreation model)
        {
            var doctors = new Doctor()
            {
                Age = model.Age,
                Name = model.Name,
            };
            await _context.Doctors.AddAsync(doctors);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var doctor = await _context.Doctors.FindAsync(id);
            var model = new DoctorForEdit()
            {
                Id = doctor.Id,
                Name = doctor.Name,
                Age = doctor.Age
            };
            return View(model);
        }

        [HttpPost]

        public async Task<IActionResult> Edit(DoctorForEdit model)
        {
            var doctors = new Doctor()
            {
                Id = model.Id,
                Age = model.Age,
                Name = model.Name,
            };
            _context.Doctors.Update(doctors);
            await _context.SaveChangesAsync();

            var appointmentsToUpdate = await _context.Appointments
                .Where(a => a.DoctorId == model.Id)
                .ToListAsync();

            foreach (var appointment in appointmentsToUpdate)
            {
                appointment.DoctorName = model.Name;
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var doctor = await _context.Doctors.FindAsync(id);
            _context.Doctors.Remove(doctor);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Controllers/PatientController.cs
using Med_Center.Data;
using Med_Center.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Med_Center.Controllers
{
    public class PatientController : Controller
    {
        private readonly MedCenterContext _context;
        public PatientController(MedCenterContext context)
        {
            _context = context;
        }
        public async Task<ActionResult> Index()
        {
            var patients = await _context.Patients.Include(d=>d.Doctor).ToListAsync();
            return View(patients);
        }
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            var model = new PatientForCreation();
            model.Doctors = await _context.Doctors.ToListAsync();
            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> Create(PatientForCreation model)
        {
            var patient = new Patient()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Age = model.Age,
                DoctorId = model.SelectedDoctorId
            };
            await _context.Patients.AddAsync(patient);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            var patient = await _context.Patients.FindAsync(id);
            var model = new PatientForEdit()
            {
                Id = id,
                FirstName = patient.FirstName,
                LastName = patient.LastName,
                Age = patient.Age,
                SelectedDoctorId = patient.DoctorId,
                Doctors = await _context.Doctors.ToListAsync()
            };
            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> Edit(PatientForEdit model)
        {
            var patient = new Patient()
            {
                Id = model.Id,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Age = model.Age,
                DoctorId = model.SelectedDoctorId
            };

            _context.Patients.Update(patient);
            await _context.SaveChangesAsync();

            var appointmentsToUpdate = await _context.Appointments
                .Where(a => a.PatientId == model.Id)
                .ToListAsync();

            foreach (var appointment in appointmentsToUpdate)
            {
                appointment.PatientName = model.FirstName + " " + model.LastName;
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        public async Task<ActionResult> Delete(int id)
        {
            var patient = await _context.Patients.FindAsync(id);
            _context.Patients.Remove(patient);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Med_Center</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Med_Center.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Med_Center</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">Doctor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="Index">Patients</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appointment" asp-action="Index">Appointments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Med_Center - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>